trigger: none

stages:
  - stage: Deploy_Stage
    displayName: "Deploy Stage"

    jobs:
      - job: Deploy_App
        displayName: "Deploy App"
        pool:
          vmImage: ubuntu-latest

        steps:
          - task: Kubernetes@1
            displayName: Deploy to AKS
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'Kube-Cluster'
              command: apply
              arguments: '-f Kubernetes/'