trigger: none



stages:
  - stage: Deploy_Stage
    displayName: "Deploy Stage"
    jobs:
      - job: Deploy_App
        displayName: "Deploy App"
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Deploying Manifest file"
              kubectl apply -f kubernetes/

              echo "Checking the Status of Pods"
              kubectl get pods

              echo "Checking the Service"
              kubectl get svc
            displayName: "Deploy to Kubernetes"