# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
pool:

stages:
  - stage: "Build The Docker Image"
    jobs:
      - job: "Docker Build"
        steps:
          - task: Docker@2
            inputs:
              repository: prachiii123/nnetflix
              tags: $(Build.BuildId)
              command: build
              Dockerfile: "**/Dockerfile"
          - task: Docker@2
            inputs:
              containerRegistry: "Docker-Hub-Connection"
              repository: prachiii123/nnetflix
              tags: $(Build.BuildId)
              command: push
              Dockerfile: "**/Dockerfile"
