---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app-deployment
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - image: prachiii123/nnetflix:1.1
          name: netflix
          ports:
            - containerPort: 80
            
